spring:
  application:
    name: consumer
  cloud:
    function:
      definition: processRiderLocation;processRiderStatus
    stream:
      bindings:
        processRiderLocation-in-0:
          destination: my-topic
        processRiderStatus-in-0:
          destination: my-topic-2
      poller:
        fixed-delay: 1000

      binders:
        kafka:
          type: kafka
          environment:
            spring:
              kafka:
                bootstrap-servers: localhost:9092
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: "*"
#        spring.json.value.default.type: com.southdragon.consumer.RiderLocation
server:
  port: 8081
